# permissions for end users to view credentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credential-viewer-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - credentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - credentials/status
  verbs:
  - get
